// Package assembler - Copyright © 2020 Jonathan Whitaker <github@whitaker.io>.
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

package assembler

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/whitaker-io/machine/lang/ast"
)

// Request is everything one emission needs.
//
// IT IS A STRUCT RATHER THAN SIX PARAMETERS because six positional arguments of
// four different shapes is a call site nobody can read, and the module's linter
// caps a signature at five for that reason. Naming them at the call site also
// means adding one later cannot silently reorder an existing caller's arguments.
type Request struct {
	// File is the parsed source.
	File *ast.File
	// Programs are its flows' graphs, in file order.
	Programs []*Program
	// Plans are the matching lowered plans, in the same order.
	Plans []*Plan
	// Config is the generated package name and handle qualifier.
	Config Config
	// Source is the .flow path, used for the source stamp and the output name.
	Source string
	// Types is the loaded package set's view, or nil when none was loaded.
	Types *Types
	// Registrations are the gob registrations this file's package must emit,
	// already deduplicated and sorted by the driver.
	Registrations []Registration
}

// generatedMarker is line 1 of every emitted file, exactly.
const generatedMarker = "// Code generated by github.com/whitaker-io/machine/lang/assembler; DO NOT EDIT."

// runtimeImport is the one import the emitter adds on its own.
const runtimeImport = `machine "github.com/whitaker-io/machine/v4"`

// emitter accumulates one generated file.
type emitter struct {
	buf   strings.Builder
	diags []Diagnostic
	// lines maps a generated line number to the .flow position it came from, so
	// a type error reported against generated source can be re-pointed at the
	// source the author actually wrote.
	lines map[int]ast.Position
	// line is the generated line most recently written.
	line int
	// synth holds one derivation per flow, in plan order.
	synth []*synthesis
}

// synthesized writes every derived clone and duplicator.
func (e *emitter) synthesized() {
	for _, s := range e.synth {
		if body := s.Functions(); body != "" {
			e.writeln("// Deep-copy functions derived from the payload types. A tee copies into")
			e.writeln("// both branches and every state key requires a cloner, so these are")
			e.writeln("// synthesized rather than assumed: a shallow copy would leave two branches")
			e.writeln("// sharing the same backing memory, silently.")
			e.writeln(body)
		}
	}
}

// Generate turns one file's plans into one generated Go file.
//
// THE ORDER IS FIXED and every part of it is load-bearing: the marker line tells
// every tool in the ecosystem this file is not to be edited, the source stamp
// says which .flow produced it, the preamble carries the type-inference helpers,
// and the wiring functions come last so everything they reference is already
// declared.
func Generate(req Request) (Generated, []Diagnostic) {
	file, plans, cfg, source := req.File, req.Plans, req.Config, req.Source
	e := &emitter{lines: map[int]ast.Position{}}
	if diags := e.synthesize(req); len(diags) != 0 {
		return Generated{Name: generatedName(source)}, diags
	}
	e.header(source)
	e.packageClause(cfg, plans)
	e.imports(file, plans, req.Registrations)
	e.writeln(preamble)
	e.synthesized()
	e.verbatimFuncs(file)
	e.declarations(file)
	e.registrations(req.Registrations)
	// The synthesis slice is built per PROGRAM in the same order the plans are,
	// so a plan takes the derivation belonging to its own flow.
	//
	// AN EMBEDDED PLAN IS SKIPPED WHOLE — no wiring function, no ingest struct, no
	// handle declarations. It is a signature-carrying flow, which is inlined into
	// its consumers; wiring one on its own emits a body reading an unbound `in`.
	for i, plan := range plans {
		if plan.Embedded {
			continue
		}
		var s *synthesis
		if i < len(e.synth) {
			s = e.synth[i]
		}
		e.wire(plan, s)
	}

	return e.formatted(source)
}

// formatted runs gofmt over the emitted bytes.
//
// A FILE THAT DOES NOT PARSE IS HANDED BACK UNFORMATTED WITH A DIAGNOSTIC, not
// swallowed: the unformatted bytes are what a reader needs to see why, and
// returning nothing would leave the failure with no evidence attached.
func (e *emitter) formatted(source string) (Generated, []Diagnostic) {
	src := e.buf.String()
	out, err := format.Source([]byte(src))
	if err != nil {
		e.diags = append(e.diags, Diagnostic{
			Message: fmt.Sprintf("the generated file for %s is not valid Go: %v", source, err),
		})

		return Generated{Name: generatedName(source), Source: []byte(src)}, e.diags
	}

	return Generated{Name: generatedName(source), Source: out}, e.diags
}

// synthesize derives every clone and duplicator the file needs.
//
// IT RUNS FIRST. A tee needs a Duplicator and every var's NewKey needs a cloner,
// both derived from type structure, and a file missing either is refused before a
// line is written rather than emitted half-formed.
func (e *emitter) synthesize(req Request) []Diagnostic {
	for _, p := range req.Programs {
		s := newSynthesis(p, req.Types)
		e.diags = append(e.diags, s.Diagnostics()...)
		e.synth = append(e.synth, s)
	}

	return e.diags
}

// anyPlanCheckpoints reports whether any EMITTED flow in the file carries a
// checkpoint.
//
// IT ASKS ABOUT THE EMITTED SET RATHER THAN THE LOWERED ONE, because its single
// consumer is the conditional "fmt" import and only a wiring function uses fmt.
// An embedded plan gets no wiring function, so counting one here would import fmt
// for a file that never references it — and an unused import does not compile. A
// checkpoint inside an embedded flow still reaches this answer through the
// CONSUMER whose plan inlined it.
func anyPlanCheckpoints(plans []*Plan) bool {
	for _, plan := range plans {
		if !plan.Embedded && planCheckpoints(plan) {
			return true
		}
	}

	return false
}

// generatedName renders the output file name for a .flow source.
func generatedName(source string) string {
	base := source
	if at := strings.LastIndex(base, "/"); at >= 0 {
		base = base[at+1:]
	}

	return strings.TrimSuffix(base, ".flow") + ".flow.go"
}

// writeln appends a line and advances the line map cursor.
func (e *emitter) writeln(text string) {
	_, _ = e.buf.WriteString(text)
	_, _ = e.buf.WriteString("\n")
	e.line += strings.Count(text, "\n") + 1
}

// writeAt appends a line and records the .flow position it came from.
func (e *emitter) writeAt(pos ast.Position, text string) {
	e.lines[e.line+1] = pos
	e.writeln(text)
}

// header writes the two lines every generated file opens with.
func (e *emitter) header(source string) {
	e.writeln(generatedMarker)
	e.writeln("// source: " + source)
	e.writeln("")
}

// packageClause writes the package doc and clause.
//
// THE DOC CARRIES THE HOST JOURNAL CONTRACT, because the host is who has to act
// on it and the generated file is what they read.
func (e *emitter) packageClause(cfg Config, plans []*Plan) {
	e.writeln("// Package " + cfg.Package + " is generated from a .flow source. Do not edit it:")
	e.writeln("// every regeneration rewrites it whole.")
	e.journalContract()
	if len(plans) > 0 {
		e.writeln("//")
		e.writeln("// Flows in this file: " + flowNames(plans) + ".")
	}
	e.writeln("package " + cfg.Package)
	e.writeln("")
}

// journalContract writes the host journal contract into the package doc.
//
// It is split from the clause above only because the module's linter caps a
// function at twenty statements; the two together are one doc comment.
func (e *emitter) journalContract() {
	e.writeln("//")
	e.writeln("// THE HOST OWNS THE JOURNAL. A flow containing a checkpoint clause needs a")
	e.writeln("// recovery journal, and this package does not build one: the host constructs")
	e.writeln("// its Machine and passes machine.OptionJournal. Generated code deliberately")
	e.writeln("// cannot reach the journal itself, only ask whether one is wired, because a")
	e.writeln("// generated file must not learn a deployment's replication configuration.")
	e.writeln("//")
	e.journalRefusalContract()
}

// journalRefusalContract writes the second half of the host journal contract.
//
// It is split from journalContract above only because the module's linter caps a
// function at twenty statements; the three together are one doc comment.
func (e *emitter) journalRefusalContract() {
	e.writeln("// WHAT HAPPENS WHEN THE HOST FORGETS. Every Wire function below returns its")
	e.writeln("// flow's ingest struct and an error, uniformly, whether or not its flow")
	e.writeln("// checkpoints and whether or not the host means to feed it programmatically —")
	e.writeln("// the signature is one contract rather than two, so a host's call site never")
	e.writeln("// depends on a property of the .flow source it cannot see. For a flow that DOES")
	e.writeln("// checkpoint, Wire checks for a journal BEFORE declaring any node and returns")
	e.writeln("// the ZERO ingest struct beside an error naming the flow and")
	e.writeln("// machine.OptionJournal, leaving the machine untouched. The zero struct's")
	e.writeln("// fields are nil funcs, so a host that ignores the error and pushes panics")
	e.writeln("// rather than dropping the value silently.")
	e.writeln("//")
	e.writeln("// THE RUNTIME'S OWN REFUSAL IS A DIFFERENT ONE, and it arrives later. A")
	e.writeln("// checkpointed node declared on a journal-less machine records a declaration")
	e.writeln("// error that Start returns; Wire itself returns nothing on the runtime's")
	e.writeln("// behalf. So the check here is what turns a failure at Start, naming a node")
	e.writeln("// and a Go option the .flow author never wrote, into one at Wire naming the")
	e.writeln("// flow and the option the host controls.")
}

// flowNames renders the flow list for the package doc.
func flowNames(plans []*Plan) string {
	names := make([]string, 0, len(plans))
	for _, plan := range plans {
		names = append(names, plan.Flow)
	}

	return strings.Join(names, ", ")
}

// imports writes the import block: the runtime, plus every import the .flow
// source declared, verbatim.
//
// fmt IS CONDITIONAL. It is needed only by the Wire-time journal refusal, which
// only a checkpointing flow emits, and an unused import does not compile.
//
// encoding/gob IS CONDITIONAL ON THE SAME TERMS, and for the same reason: it is
// referenced only by the registration init below, so a file needing no
// registration carries neither an empty init nor an unused import.
func (e *emitter) imports(file *ast.File, plans []*Plan, regs []Registration) {
	e.writeln("import (")
	if anyPlanCheckpoints(plans) || len(regs) > 0 {
		if len(regs) > 0 {
			e.writeln("\t\"encoding/gob\"")
		}
		if anyPlanCheckpoints(plans) {
			e.writeln("\t\"fmt\"")
		}
		e.writeln("")
	}
	e.writeln("\t" + runtimeImport)
	for _, decl := range file.Decls {
		imp, ok := decl.(ast.ImportDecl)
		if !ok {
			continue
		}
		line := "\t"
		if imp.Alias != nil {
			line += imp.Alias.Name + " "
		}
		// The parser stores the path WITH its quotes, so re-quoting it here would
		// emit a doubled literal that does not parse.
		e.writeAt(imp.Start, line+quotedPath(imp.Path))
	}
	e.writeln(")")
	e.writeln("")
}

// quotedPath renders an import path as a Go string literal, whether or not the
// parser already kept its quotes.
func quotedPath(path string) string {
	if strings.HasPrefix(path, `"`) && strings.HasSuffix(path, `"`) {
		return path
	}

	return `"` + path + `"`
}

// registrations writes the gob registrations the serialization derivation
// required, one per line inside a single init.
//
// AN init RATHER THAN A Wire PREAMBLE, and the difference is observable. A
// registration is a property of the PACKAGE: the same type may cross a boundary
// in two flows, a host may wire one flow and decode a checkpoint written by
// another, and gob consults its registry the first time it meets an interface
// slot rather than when anything was wired. An init runs once at package load
// whatever the host calls; a preamble registers only what the host happened to
// wire, which is a registry that depends on call order.
//
// THE VALUE IS *new(T) RATHER THAN T{}, because a declared spelling is not always
// a composite-literal shape — a pointer, a slice of a named type and a generic
// instantiation are all legal declarations and only one of them takes braces.
func (e *emitter) registrations(regs []Registration) {
	if len(regs) == 0 {
		return
	}

	e.writeln("// init registers every type the serialization derivation found at an interface")
	e.writeln("// site, so the gob decoder can reconstruct it by name. It runs once at package")
	e.writeln("// load, whatever the host wires and in whatever order.")
	e.writeln("func init() {")
	for _, reg := range regs {
		e.writeln("\tgob.Register(*new(" + reg.Spelling + "))")
	}
	e.writeln("}")
	e.writeln("")
}

// verbatimFuncs writes the func declarations the .flow source carried, pasted
// unchanged.
func (e *emitter) verbatimFuncs(file *ast.File) {
	for _, decl := range file.Decls {
		if fn, ok := decl.(ast.FuncDecl); ok {
			e.writeAt(fn.Start, "func "+fn.Name.Name+fn.Body.Text)
			e.writeln("")
		}
	}
}

// declarations writes the file-level const and param declarations.
func (e *emitter) declarations(file *ast.File) {
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case ast.ConstDecl:
			spelling := ""
			if d.Type != nil {
				spelling = " " + d.Type.Text
			}
			e.writeAt(d.Start, "const "+d.Name.Name+spelling+" = "+d.Value.Text)
		case ast.ParamDecl:
			// A param is a var with a default: the host may reassign it before
			// wiring, which a const would forbid.
			e.writeAt(d.Start, "var "+d.Name.Name+" "+d.Type.Text+" = "+d.Default.Text)
		}
	}
	e.writeln("")
}
