// Code generated by github.com/whitaker-io/machine/lang/assembler; DO NOT EDIT.
// source: pipeline.flow

// Package generated is generated from a .flow source. Do not edit it:
// every regeneration rewrites it whole.
//
// THE HOST OWNS THE JOURNAL. A flow containing a checkpoint clause needs a
// recovery journal, and this package does not build one: the host constructs
// its Machine and passes machine.OptionJournal. Generated code deliberately
// cannot reach the journal itself, only ask whether one is wired, because a
// generated file must not learn a deployment's replication configuration.
//
// WHAT HAPPENS WHEN THE HOST FORGETS. Every Wire function below returns its
// flow's ingest struct and an error, uniformly, whether or not its flow
// checkpoints and whether or not the host means to feed it programmatically —
// the signature is one contract rather than two, so a host's call site never
// depends on a property of the .flow source it cannot see. For a flow that DOES
// checkpoint, Wire checks for a journal BEFORE declaring any node and returns
// the ZERO ingest struct beside an error naming the flow and
// machine.OptionJournal, leaving the machine untouched. The zero struct's
// fields are nil funcs, so a host that ignores the error and pushes panics
// rather than dropping the value silently.
//
// THE RUNTIME'S OWN REFUSAL IS A DIFFERENT ONE, and it arrives later. A
// checkpointed node declared on a journal-less machine records a declaration
// error that Start returns; Wire itself returns nothing on the runtime's
// behalf. So the check here is what turns a failure at Start, naming a node
// and a Go option the .flow author never wrote, into one at Wire naming the
// flow and the option the host controls.
//
// Flows in this file: orders.
package generated

import (
	machine "github.com/whitaker-io/machine/v4"
	"strings"
)

// flowReadsOf declares a node's read capabilities, carrying the node's input
// type through the node function's own signature.
//
// The function is IGNORED. It is a parameter only so Go can infer U: WithReads
// takes KeyRefs, which name no type, and a generic call's type argument is not
// inferred from the parameter it is passed into.
func flowReadsOf[U, V any](_ machine.Transformation[U, V], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithReads[U](refs...)
}

// flowWritesOf declares a node's write capabilities, on the same terms.
//
// A write capability does NOT imply a read capability: a node that reads,
// modifies and writes one handle declares it in both.
func flowWritesOf[U, V any](_ machine.Transformation[U, V], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithWrites[U](refs...)
}

// flowReadsOfFilter is flowReadsOf for a branch, whose predicate is a Filter
// rather than a Transformation and so carries its type through a different
// signature.
func flowReadsOfFilter[U any](_ machine.Filter[U], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithReads[U](refs...)
}

// flowWritesOfFilter is flowWritesOf for a branch.
func flowWritesOfFilter[U any](_ machine.Filter[U], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithWrites[U](refs...)
}

func Bill(f machine.Frame[Order]) Receipt {
	count, _, err := f.Load(seen)
	if err != nil {
		panic(err)
	}
	if err := f.Save(seen, count+1); err != nil {
		panic(err)
	}
	f.Set(attempt, f.Get(attempt)+1)
	return Receipt{ID: strings.ToUpper(f.Value().ID), Seen: count + 1}
}

const Retries int = 3

var Endpoint string = ":8080"

// OrdersOnError is the flow-level error handler orders declares.
//
// WIRE CANNOT INSTALL IT. A machine's error handler is a machine.New option and
// Wire is handed a machine that is already built, so the host passes
// machine.OptionErrorHandler(OrdersOnError) when constructing it. Without that,
// the flow runs under the runtime's default handler and this declaration has no
// effect.
var OrdersOnError = machine.ErrorHandler[any](PageOnCall)

// State handles for the orders flow. The names are qualified because the
// runtime holds every key and cell in one process-global namespace.
var (
	attempt = machine.NewKey[int]("acme.orders.attempt", func(v int) int { return v })
	seen    = machine.NewCell[int]("acme.orders.seen")
)

// OrdersIngests carries one typed ingest per source statement in the orders flow.
//
// Each field pushes a value into its source as if the source's transport had
// delivered it, so a host can feed the flow programmatically. A field is a nil
// func on the zero struct, which is what Wire returns beside a non-nil error.
type OrdersIngests struct {
	// Ingest feeds the ingest source.
	Ingest machine.Ingest[Order]
}

// WireOrders declares the orders flow on m and returns its ingests.
//
// IT RETURNS OrdersIngests AND error UNCONDITIONALLY. A flow with no
// checkpoint returns a nil error, and a flow whose sources are all driven by
// their transports returns a struct the host is free to ignore. The signature is
// one contract rather than two, so a caller never has to know whether the .flow
// source happens to checkpoint or to be fed programmatically, and a regeneration
// cannot silently change how this is called.
//
// THE ZERO STRUCT IS NOT USABLE. On a non-nil error the returned struct is the
// zero value and every ingest field is a nil func, so a caller that ignores the
// error and pushes panics rather than dropping the value silently.
func WireOrders(m *machine.Machine) (OrdersIngests, error) {
	ingest, ingest_ingest := m.Source[Order]("ingest", machine.WithEdge(Poll()), machine.WithEdge(machine.Channel[Order](0)))
	charge := ingest.Map("charge", Bill, flowReadsOf(Bill, attempt), flowWritesOf(Bill, seen), machine.WithErrorHandler(NodeFailed))
	done := charge.Map("done", Store)
	done.Drop("done#drain")

	return OrdersIngests{
		Ingest: ingest_ingest,
	}, nil
}
