// Code generated by github.com/whitaker-io/machine/lang/assembler; DO NOT EDIT.
// source: pipeline.flow

// Package generated is generated from a .flow source. Do not edit it:
// every regeneration rewrites it whole.
//
// THE HOST OWNS THE JOURNAL. A flow containing a checkpoint clause needs a
// recovery journal, and this package does not build one: the host constructs
// its Machine and passes machine.OptionJournal. Generated code deliberately
// cannot reach the journal itself, only ask whether one is wired, because a
// generated file must not learn a deployment's replication configuration.
//
// WHAT HAPPENS WHEN THE HOST FORGETS. Every Wire function below returns error,
// uniformly, whether or not its flow checkpoints — the signature is one
// contract rather than two, so a host's call site never depends on a property
// of the .flow source it cannot see. For a flow that DOES checkpoint, Wire
// checks for a journal BEFORE declaring any node and returns an error naming
// the flow and machine.OptionJournal, leaving the machine untouched.
//
// THE RUNTIME'S OWN REFUSAL IS A DIFFERENT ONE, and it arrives later. A
// checkpointed node declared on a journal-less machine records a declaration
// error that Start returns; Wire itself returns nothing on the runtime's
// behalf. So the check here is what turns a failure at Start, naming a node
// and a Go option the .flow author never wrote, into one at Wire naming the
// flow and the option the host controls.
//
// Flows in this file: routing.
package generated

import (
	machine "github.com/whitaker-io/machine/v4"
)

// flowReadsOf declares a node's read capabilities, carrying the node's input
// type through the node function's own signature.
//
// The function is IGNORED. It is a parameter only so Go can infer U: WithReads
// takes KeyRefs, which name no type, and a generic call's type argument is not
// inferred from the parameter it is passed into.
func flowReadsOf[U, V any](_ machine.Transformation[U, V], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithReads[U](refs...)
}

// flowWritesOf declares a node's write capabilities, on the same terms.
//
// A write capability does NOT imply a read capability: a node that reads,
// modifies and writes one handle declares it in both.
func flowWritesOf[U, V any](_ machine.Transformation[U, V], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithWrites[U](refs...)
}

// flowReadsOfFilter is flowReadsOf for a branch, whose predicate is a Filter
// rather than a Transformation and so carries its type through a different
// signature.
func flowReadsOfFilter[U any](_ machine.Filter[U], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithReads[U](refs...)
}

// flowWritesOfFilter is flowWritesOf for a branch.
func flowWritesOfFilter[U any](_ machine.Filter[U], refs ...machine.KeyRef) machine.NodeOption[U] {
	return machine.WithWrites[U](refs...)
}

// WireRouting declares the routing flow on m.
//
// IT RETURNS error UNCONDITIONALLY. A flow with no checkpoint returns nil; the
// signature is one contract rather than two, so a caller never has to know
// whether the .flow source happens to checkpoint, and a regeneration cannot
// silently change how this is called.
func WireRouting(m *machine.Machine) error {
	ingest, _ := m.Source[Order]("ingest", machine.WithEdge(Poll()))
	billable, routeRest := ingest.If("route", func(f machine.Frame[Order]) bool {
		ingest := f.Value()
		_ = ingest
		return ingest.Kind == "card" || ingest.Kind == "wallet"
	})
	refundable, other := routeRest.If("route#1", func(f machine.Frame[Order]) bool {
		ingest := f.Value()
		_ = ingest
		return (IsRefund(ingest))
	})
	charge := billable.Map("charge", Bill)
	kept, lost := charge.If("settle", Succeeded)
	store := kept.Map("store", Store)
	store.Drop("store#drain")
	lost.Drop("lost#drop")
	hold := refundable.Map("hold", Quarantine)
	hold.Drop("hold#drain")
	other.Send(refundable)

	return nil
}
